title: mspath.github.io
author: markus spath
description: notes
site.url: "https://mspath.github.io"
show_excerpts: true
permalink: /:categories/:title.html
date_format: "%b %-d, %Y"

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "default"

