title: mspath.github.io
author: markus spath
description: github repo notes 
site.url: "https://mspath.github.io"
show_excerpts: true
permalink: /:year/:month/:title.html
date_format: "%Y-%m-%d"

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "content"
  -
    scope:
      path: "" 
      type: "pages"
    values:
      layout: "page"
